// lib/templates/form-sections/PersonalInfoSection.tsx
"use client";

import { Field, FieldGroup, FieldLabel, FieldSet } from "@/components/ui/field";
import { UserRound } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Controller, useFormContext, useFieldArray } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Plus, Trash2 } from "lucide-react";
export default function PersonalInfoSection() {
  const {
    control,
    formState: { errors },
  } = useFormContext();
const { fields, append, remove } = useFieldArray({ control, name: "links" });
  return (
    <div className="w-full border border-border p-6 shadow-(--shadow-card) bg-white rounded-4xl">
      <FieldSet>
        <FieldGroup>
          <Field>
            <div className="flex gap-2 mb-6">
              <FieldLabel className="size-12 rounded-lg flex justify-center items-center bg-primary-light">
                <UserRound color="#5B5FEF" />
              </FieldLabel>
              <div>
                <FieldLabel className="text-lg font-bold">
                  Personal Details
                </FieldLabel>
                <FieldLabel className="text-xs tracking-wider font-light text-foreground-subtle">
                  This appears in the header of your resume — it's never
                  generated by AI.
                </FieldLabel>
              </div>
            </div>

            <FieldLabel className="text-base font-bold">Full name</FieldLabel>
            <Controller
              name="fullName"
              control={control}
              render={({ field }) => (
                <Input {...field} placeholder="e.g. Jahanie Calipa Aminoden" />
              )}
            />
            {errors.fullName && (
              <p className="text-xs text-red-500 mt-1">
                {errors.fullName.message as string}
              </p>
            )}
          </Field>

          <div className="grid grid-cols-2 gap-4 mt-2">
            <Field>
              <FieldLabel className="text-base font-bold">Age</FieldLabel>
              <Controller
                name="age"
                control={control}
                render={({ field }) => <Input {...field} placeholder="18" />}
              />
              {errors.age && (
                <p className="text-xs text-red-500 mt-1">
                  {errors.age.message as string}
                </p>
              )}
            </Field>

            <Field>
              <FieldLabel className="text-base font-bold">
                Date of birth
              </FieldLabel>
              <Controller
                name="dateOfBirth"
                control={control}
                render={({ field }) => (
                  <Input {...field} placeholder="May 15, 2008" />
                )}
              />
              {errors.dateOfBirth && (
                <p className="text-xs text-red-500 mt-1">
                  {errors.dateOfBirth.message as string}
                </p>
              )}
            </Field>
          </div>

          <Field className="mt-2">
            <FieldLabel className="text-base font-bold">Nationality</FieldLabel>
            <Controller
              name="nationality"
              control={control}
              render={({ field }) => (
                <Input {...field} placeholder="Filipino" />
              )}
            />
            {errors.nationality && (
              <p className="text-xs text-red-500 mt-1">
                {errors.nationality.message as string}
              </p>
            )}
          </Field>

          <Field className="mt-2">
            <FieldLabel className="text-base font-bold">Address</FieldLabel>
            <Controller
              name="address"
              control={control}
              render={({ field }) => (
                <Input
                  {...field}
                  placeholder="Davao City, Ecoland, Philippines"
                />
              )}
            />
            {errors.address && (
              <p className="text-xs text-red-500 mt-1">
                {errors.address.message as string}
              </p>
            )}
          </Field>

          <div className="grid grid-cols-2 gap-4 mt-2">
            <Field>
              <FieldLabel className="text-base font-bold">Phone</FieldLabel>
              <Controller
                name="phone"
                control={control}
                render={({ field }) => (
                  <Input {...field} placeholder="09XX XXX XXXX" />
                )}
              />
              {errors.phone && (
                <p className="text-xs text-red-500 mt-1">
                  {errors.phone.message as string}
                </p>
              )}
            </Field>

            <Field>
              <FieldLabel className="text-base font-bold">Email</FieldLabel>
              <Controller
                name="email"
                control={control}
                render={({ field }) => (
                  <Input {...field} type="email" placeholder="you@gmail.com" />
                )}
              />
              {errors.email && (
                <p className="text-xs text-red-500 mt-1">
                  {errors.email.message as string}
                </p>
              )}
            </Field>
          </div>
          <div className="mt-2">
            <FieldLabel className="text-base font-bold">Links</FieldLabel>
            {fields.map((field, index) => (
              <div key={field.id} className="flex gap-2 mt-2">
                <Controller
                  name={`links.${index}.label`}
                  control={control}
                  render={({ field }) => (
                    <Input
                      {...field}
                      placeholder="LinkedIn"
                      className="w-1/3"
                    />
                  )}
                />
                <Controller
                  name={`links.${index}.url`}
                  control={control}
                  render={({ field }) => (
                    <Input
                      {...field}
                      placeholder="https://linkedin.com/in/..."
                    />
                  )}
                />
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => remove(index)}
                >
                  <Trash2 className="size-4" />
                </Button>
              </div>
            ))}
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="mt-4"
              onClick={() =>
                append({ id: crypto.randomUUID(), label: "", url: "" })
              }
            >
              <Plus className="size-4 mr-1" /> Add link
            </Button>
          </div>
        </FieldGroup>
      </FieldSet>
    </div>
  );
}
